env:
  global:
    - CC_TEST_REPORTER_ID=4393cc61df3e0a84478c986b2011b8144a482d5d883f212aee7c0133123455d8
language: node_js
node_js:
  - "8"
  - "10"
os:
  - linux
  - osx
cache:
  directories:
    - node_modules
addons:
  apt:
    packages:
      - libssl-dev
  homebrew:
    packages:
      - openssl
before_script:
  - wget https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tar.xz
  - tar -xf Python-3.7.0.tar.xz
  - (cd Python-3.7.0 && ./configure --prefix=$HOME/.local && make && make altinstall)
  - export PATH=$HOME/.local/bin:$PATH
  - which python3.7
  - which pip3.7
  - pip3.7 install --upgrade black
  - which black
  - OS_NAME=$(uname | tr A-Z a-z)
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-${OS_NAME}-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - which black
  - black --version
  - npm run build
  - npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  email:
    on_success: never
    on_failure: change
